apiVersion: v1
kind: Service
metadata:
  name: patient-core-service
  namespace: healthcare
  labels:
    app: patient-core-service
spec:
  selector:
    app: patient-core-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  # ClusterIP: reachable only within the cluster.
  # Appointment Service uses DNS name "patient-core-service:8080" to call this.
  type: ClusterIP
