apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "patient-appointment-service.mysqlServiceName" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patient-appointment-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage }}
