apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patient-appointment-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patient-appointment-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.mysql.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.mysql.rootPassword | b64enc | quote }}
