apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-db-pvc
  namespace: healthcare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # Minikube default; omit to use cluster default
