apiVersion: v1
kind: Service
metadata:
  name: appointment-db
  namespace: healthcare
  labels:
    app: appointment-db
spec:
  selector:
    app: appointment-db
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP
