apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appointment-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "appointment-service.mysqlServiceName" . }}
  DB_PORT: {{ .Values.mysql.port | quote }}
  DB_NAME: {{ .Values.mysql.database | quote }}
  # Feign client target — must match the K8s Service name of patient-service
  PATIENT_SERVICE_URL: {{ .Values.patientService.url | quote }}
