apiVersion: v1
kind: Service
metadata:
  name: {{ include "appointment-service.mysqlServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appointment-service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "appointment-service.mysqlServiceName" . }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP
