apiVersion: v1
kind: Secret
metadata:
  name: {{ include "patient-core-service.mysqlServiceName" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patient-core-service.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.rootPassword | b64enc | quote }}
  mysql-database: {{ .Values.mysql.database | b64enc | quote }}
