apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "patient-service.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "patient-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "patient-service.mysqlServiceName" . }}
  DB_PORT: {{ .Values.mysql.port | quote }}
  DB_NAME: {{ .Values.mysql.database | quote }}
